
bridge_name = "Killer(R) Wi-Fi 6E AX1675i 160MHz Wireless Network Adapter (211NGW)"

Vagrant.configure(2) do |config|

    # netbox
    config.vm.define "netbox" do |n|
        n.vm.box = "mapickett/ubuntu-box"
        n.vm.hostname = "netbox.lab.local"
        n.vm.network "public_network", bridge: bridge_name, ip: "192.168.0.15"
        n.vm.provider "virtualbox" do |vb|
            vb.cpus = 4
            vb.memory = 8192
        end
    end
end
